[book]
authors = ["jzbor"]
language = "en"
multilingual = false
src = "docs"
title = "MARSWM Documentation"

[build]
build-dir = "target/book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
